version: '3.9'

services:
  twingate_connector:
    container_name: twingate
    image: twingate/connector:latest
    restart: always
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - TWINGATE_API_ENDPOINT=/connector.stock
      - TWINGATE_NETWORK=<TENANT NAME>  # Set the environment variable "TWINGATE_NETWORK"
      - TWINGATE_ACCESS_TOKEN=<ACCESS TOKEN>  # Set the environment variable "TWINGATE_ACCESS_TOKEN"
      - TWINGATE_REFRESH_TOKEN=<REFRESH TOKEN>  # Set the environment variable "TWINGATE_REFRESH_TOKEN"
      - TWINGATE_LABEL_HOSTNAME=<HOST NAME>  # Set the environment variable "TWINGATE_LABEL_HOSTNAME"
      - TWINGATE_LOG_ANALYTICS=v2 #
      - TWINGATE_LOG_LEVEL=3
    sysctls:
      # Set the sysctl parameter "net.ipv4.ping_group_range" to allow user IDs in the range 0 to 65535 to create ICMP echo request (ping) sockets
      - "net.ipv4.ping_group_range=0 65535"