version: '3.9'

services:
  twingate:
    container_name: twingate
    image: twingate/connector:latest
    environment:
      - TWINGATE_NETWORK=<TENANT NAME>
      - TWINGATE_ACCESS_TOKEN=<ACCESS TOKEN>
      - TWINGATE_REFRESH_TOKEN=<REFRESH TOKEN>
      # - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      # - TWINGATE_API_ENDPOINT=/connector.stock
      # -- (Optional) Change loglevel
      # - TWINGATE_LOG_LEVEL=3
      # -- (Optional) Add custom DNS Server
      # - TWINGATE_DNS=10.20.0.1
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
    # -- (Optional) When using a custom network
    networks:
      - frontend
    restart: unless-stopped
    
# -- (Optional) When using a custom network
networks:
  frontend:
    # -- (Optional) When attaching an external network
    external: true